[theme]
base = "light"
primaryColor = "#0F766E"
backgroundColor = "#FBFBF9"
secondaryBackgroundColor = "#EFF2F1"
textColor = "#171A1F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
