[theme]
base = "light"
primaryColor = "#5b42dc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f4fd"
textColor = "#101828"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
